name = "uf-rewriter"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "uf-rewriter"
routes = [
    { pattern = "test.ultrafilter.cc", custom_domain = true, zone_name = "ultrafilter.cc" }
]

[env.staging]
name = "uf-rewriter-staging"

# Secrets configuration (set with: npx wrangler secret put GEMINI_API_KEY)
# No secrets should be stored in this file - use Cloudflare Workers secrets instead
